chore: update links and instruction
software-challenge/docs pull request #104
Opened 2024-07-14 15:55 UTC by maxblan

2024-07-17 06:59 UTC, xeruf requested changes
waarum ein wechsel aufs JRE?

2024-07-17 06:59 UTC, xeruf commented on hyperbook/book/entwicklung/installation-von-java.md
> +Um Java 11 JRE auf einem Windows-System mit `winget` zu installieren, führen Sie den folgenden Befehl im Windows Terminal aus:
hier muss auf jeden Fall ein JDK verlinkt sein, nicht JRE

2024-07-17 06:59 UTC, xeruf commented on hyperbook/book/entwicklung/installation-von-java.md
> +dann reicht das JRE vollkommen aus. Möchte man auch eigene Programme schreiben,
sembr.org beachten - Zeilenumbrüche beim Satzende

2024-07-17 06:59 UTC, xeruf commented on hyperbook/book/entwicklung/installation-von-java.md
> +Um Java 11 JRE auf einem Windows-System mit `winget` zu installieren, führen Sie den folgenden Befehl im Windows Terminal aus:
außerden solte eine windows-spezifische anleitung unter einem windows-header stehen, nicht unter generell `Installation`

2024-07-18 08:40 UTC, maxblan commented on hyperbook/book/entwicklung/installation-von-java.md
> +Um Java 11 JRE auf einem Windows-System mit `winget` zu installieren, führen Sie den folgenden Befehl im Windows Terminal aus:
My bad. Habe ich verwechselt ^^

2024-12-02 10:41 UTC, merged