/penguins/regeln: resolves #69
software-challenge/docs pull request #70
Opened 2022-09-02 10:04 UTC by FalconsSky

#69

2022-09-02 15:54 UTC, jnccd requested changes

2022-09-02 15:54 UTC, jnccd commented on hyperbook/book/spiele/penguins/regeln.md
> +    - Um eine symethrische Spielerfahrung zu bieten, wird diese Hälfte dupliziert und dann an seiner horizontalen und vertikalen Achse gespiegelt und den restlichen $32$ Feldern hinzugefügt.
> an seiner horizontalen und vertikalen Achse gespiegelt 

Soweit ich das sehe wird das Board nur einmal an seiner Gegendiagonalen gespiegelt

2022-09-02 15:54 UTC, jnccd commented on hyperbook/book/spiele/penguins/regeln.md
> +- Wenn $F_n$ ein Feld auf dem Spielbrett is, mit $0\le n\le 63$, dann sei $f_{F_n}$ die Zahl an Fischen auf einem Feld, mit $0\le f_{F_n}\le 4$.
Mathematische Varaiblen sind immer ganz nett, aber wenn ich das richtig sehe willst du hiermit nur aussagen, dass auf jedem Feld 0 bis 4 Fische sind
Ich denke man kann hier auch schreiben: Auf jedem Feld sind 0 bis 4 Fische
Das ist kürzer 😅

2022-09-02 15:54 UTC, jnccd commented
Ansonsten sieht es nice aus

2022-09-02 16:18 UTC, jnccd requested changes

2022-09-02 16:18 UTC, jnccd commented on hyperbook/book/spiele/penguins/regeln.md
> +- Auf dem Spielbrett können $\le 136$ Fische platziert werden, wobei stets auf $\ge4$ Feldern keine Fische am Anfang sein werden.
Was ist deine Rechnung für 136?
Wenn ich [das](https://github.com/software-challenge/backend/blob/main/plugin/src/main/kotlin/sc/plugin2023/Board.kt#L65) durchgehe haben wir 8 * 9 = 72 remainingFish und nextInt(72) gibt eine zufällige Zahl von 0 bis 71 zurück.
Weiter ist es dann so, dass sobald remainingFish unter 5 ist, also 0 bis 4 ist, nur noch leere Felder generiert, aka wir müssen noch mal 4 abziehen und haben 67. Nachdem das ganze verdoppelt wurde haben wir dann 134 Fishe.

2022-09-03 16:44 UTC, xeruf commented on hyperbook/book/spiele/penguins/regeln.md
> +    - Um eine symethrische Spielerfahrung zu bieten, wird diese Hälfte dupliziert und dann an seiner horizontalen und vertikalen Achse gespiegelt und den restlichen $32$ Feldern hinzugefügt.
es wird 180° gedreht

2022-09-03 16:45 UTC, xeruf commented
branch name kann so bleiben, aber auch hier bitte titel anpassen :)

2022-09-03 16:47 UTC, xeruf commented on hyperbook/book/spiele/penguins/regeln.md
> +- Auf dem Spielbrett können $\le 136$ Fische platziert werden, wobei stets auf $\ge4$ Feldern keine Fische am Anfang sein werden.
Ich sehe keinen Nutzen, hier eine genaue Zahl zu geben, da der Algorithmus das bewusst variiert, ich denke da sind Erfahrungswerte nützlicher zusammen mit der Info, dass die Gesamtanzahl der Fische auf dem Brett variiert.

2022-09-03 17:09 UTC, jnccd commented on hyperbook/book/spiele/penguins/regeln.md
> +    - Um eine symethrische Spielerfahrung zu bieten, wird diese Hälfte dupliziert und dann an seiner horizontalen und vertikalen Achse gespiegelt und den restlichen $32$ Feldern hinzugefügt.
Stimmt
Das ist auch die einfachste Erklärung

2022-09-05 15:53 UTC, jnccd approved these changes
Sieht jetzt gut aus imo

2022-09-05 15:54 UTC, jnccd commented on hyperbook/book/spiele/penguins/regeln.md
> +- Auf dem Spielbrett können $\le 136$ Fische platziert werden, wobei stets auf $\ge4$ Feldern keine Fische am Anfang sein werden.
Du hast eigentlich recht, aber jetzt ist sie da 😅
und ggf hilft sie auch Erfahrung zu formen

2022-09-05 15:55 UTC, merged

2022-09-05 20:15 UTC, xeruf commented
Danke euch :)