entwicklung: replace Zufallsspieler with Spielervorlage
software-challenge/docs pull request #73
Opened 2022-09-05 12:27 UTC by FalconsSky

resolves #56

2022-09-05 12:36 UTC, xeruf commented on hyperbook/book/entwicklung/simpleclient-erweitern.md
> +Die einfachste Möglichkeit ist, die Klasse `Logic` der Spielervorlages zu
Deklinierung haut hier nicht hin ;)

2022-09-05 12:37 UTC, xeruf commented
danke, noch was kleines: PR- und commit-messages immer im Imperativ :)

2022-09-05 12:48 UTC, FalconsSky commented on hyperbook/book/entwicklung/simpleclient-erweitern.md
> +Die einfachste Möglichkeit ist, die Klasse `Logic` der Spielervorlages zu
Done 2e53372.

2022-09-05 15:37 UTC, jnccd requested changes
Hab noch einige Kleinigkeiten gefunden, ansonsten gut 😅

2022-09-05 15:37 UTC, jnccd commented on hyperbook/book/entwicklung/abgabe.md
> +Diese Anleitung beschreibt, wie man für die Java-Spielervorlage vorgehen muss.
"Diese Anleitung beschreibt, wie man mit der Java-Spielervorlage umgehen sollte." 
Hört sich für mich natürlicher an

2022-09-05 15:37 UTC, jnccd commented on hyperbook/book/entwicklung/abgabe.md
> +Man kann auch das der Spielervorlage beiliegende Ant Buildscript benutzen.
"Man kann auch das Ant Buildscript benutzen, welches der Spielervorlage beiliegt."
Wieder natürlicher imo

2022-09-05 15:37 UTC, jnccd commented on hyperbook/book/entwicklung/abgabe.md
> +Verzeichnis der Spielervorlages wechseln und mit dem Aufruf "Ant" den
Verzeichnis der Spielervorlage [...]

2022-09-05 15:37 UTC, jnccd commented on hyperbook/book/entwicklung/abgabe.md
> +    Buildfile heißt "build.xml" und liegt direkt in der Spielervorlage
[...] in de**m** Spielervorlage Ordner [...]

2022-09-05 15:37 UTC, jnccd commented on hyperbook/book/entwicklung/einrichtung-der-entwicklungsumgebung.md
> +kann man verwenden, um seinen eigenen Spieler zu programmieren. Die
[...] Den Quellcode kann man [...]

2022-09-05 15:37 UTC, jnccd commented on hyperbook/book/entwicklung/einrichtung-der-entwicklungsumgebung.md
> +DIe Spielervorlage kann man starten, indem man im Project-Explorer einen
Die Spielervorlage

2022-09-05 15:37 UTC, jnccd commented on hyperbook/book/entwicklung/einrichtung-der-entwicklungsumgebung.md
> +    (im Ordner "lib" des Spielervorlagequellcode Paketes) einstellen
des Spielervorlagen-Quellcode-Pakets

2022-09-06 06:59 UTC, FalconsSky commented
Fixed grammar issues 1267f13.

2022-09-06 13:42 UTC, jnccd approved these changes
Sieht jetzt gut aus

2022-09-07 12:20 UTC, merged