faq: add a faq page with a entry to gc
software-challenge/docs pull request #87
Opened 2022-09-15 10:17 UTC by FalconsSky

This is a first version of a faq page with info to garbage collection.

resolves #53

2022-09-23 02:28 UTC, xeruf requested changes
Quelle ist wohl https://stackoverflow.com/questions/48989515/java-garbage-collector-time-limit, oder? Vielleicht verlinken?
Die debugging flags aus dem post sind alle im cheatsheet gut mit drin, oder?

2022-09-23 02:28 UTC, xeruf commented on hyperbook/book/faq.md
> +dann frage uns gerne auf unseren [Discord](https://discord.gg/jhyF7EU),
```suggestion
dann frage uns gerne auf unserem [Discord](https://discord.gg/jhyF7EU),
```

2022-09-23 02:28 UTC, xeruf commented on hyperbook/book/faq.md
> +Die Zeit wird von Erhalt der Nachricht des Spielleiters bis zum Erreichen der Antwort des Spielers gezählt.
```suggestion
Die Zeit wird von Erhalt der Nachricht des Spielleiters
bis zum Erreichen der Antwort des Spielers gezählt.
```

2022-09-23 02:28 UTC, xeruf commented on hyperbook/book/faq.md
> +um den Zug zu berechnen. Beachtet werden kann dabei,
solche kurzen sätze sind teilweise in einer Zeile verständlicher, aber beim punkt definitiv einen linebreak setzen

2022-09-23 02:28 UTC, xeruf commented on hyperbook/book/faq.md
> +Auch die Arbeit des Garbage Collector fällt mit in die Zeit ein,
eher "einberechnen" als "einfallen"

2022-09-23 02:28 UTC, xeruf commented on hyperbook/book/faq.md
> +zu optimieren,
```suggestion
Um die Zeit, die der Garbage Collector braucht, zu optimieren, 
```
gut gemeint, aber das sind keine funktionalen teilsätze mehr - deswegen lasse ich sowas persönlich nicht algorithmisch machen ;)

2022-09-23 02:28 UTC, xeruf commented on hyperbook/book/faq.md
> +Bitte beachte, dass die folgenden Argumente nicht allgemeingültig sind. Bedeutet das für jeden Spieler separat die optimale Kombination herausgefunden werden muss.
```suggestion
Bitte beachte, dass die folgenden Argumente nicht allgemeingültig sind.
Für jeden Spieler kann eine etwas andere Kombination optimal sein.
```

2022-09-23 02:28 UTC, xeruf commented on hyperbook/book/faq.md
> +Der volle Effekt vom Garbage Collector von `System.gc()` wird gemildert.
i.e. kein stop-the-world gc

2022-09-23 02:28 UTC, xeruf commented on hyperbook/book/faq.md
> +Dieser *kann* kürzere Pausen trotz nur eines Threads bieten.
funktioniert aber glaube ich nur noch in alten java-versionen, bitte checken

2022-09-23 02:28 UTC, xeruf commented on hyperbook/book/faq.md
> +so dass die Garbage Collection häufiger erfolgen und weniger Zeit in Anspruch nehmen.
```suggestion
so dass Garbage Collection häufiger erfolgt und weniger Zeit in Anspruch nimmt.
```
oder halt komplett pluralisieren

2022-09-26 13:50 UTC, xeruf commented on hyperbook/book/faq.md
> +wo Schleifen durchlaufen werden, welche optimiert werden können.
haut leider immer noch nicht ganz hin ^^

2022-09-26 13:51 UTC, xeruf commented
bei kleinen, eindeutigen Korrekturen direkt die Konversation resolven

2022-10-04 08:41 UTC, FalconsSky commented on hyperbook/book/faq.md
> +so dass die Garbage Collection häufiger erfolgen und weniger Zeit in Anspruch nehmen.
Den Artikel würde ich lassen.

2022-10-04 08:46 UTC, FalconsSky commented on hyperbook/book/faq.md
> +wo Schleifen durchlaufen werden, welche optimiert werden können.
Das hatte ich übersehen. Wird behoben.
```suggestion
Es kann nun versucht werden, den Algorithmus zu optimieren, 
welcher genutzt wird, um den Zug zu berechnen. 
Beachtet werden kann dabei, wo Schleifen durchlaufen werden, welche optimiert werden können. 
```

2022-10-04 08:48 UTC, FalconsSky commented on hyperbook/book/faq.md
> +so dass die Garbage Collection häufiger erfolgen und weniger Zeit in Anspruch nehmen.
```suggestion
so dass die Garbage Collection häufiger erfolgt und weniger Zeit in Anspruch nimmt.
```

2022-10-04 08:50 UTC, FalconsSky commented
> Quelle ist wohl https://stackoverflow.com/questions/48989515/java-garbage-collector-time-limit, oder? Vielleicht verlinken? Die debugging flags aus dem post sind alle im cheatsheet gut mit drin, oder?

Ich habe mich zum großen Teil auf deinen Post bezogen, ja. Ich hielt es allerdings für überflüssig diesen zu verlinken, da dieser auch zum Teil nicht mehr up-to-date ist. Da du allerdings der Autor bist, überlasse ich dir die Entscheidung, ob du den Post verlinkt haben möchtest.

2022-11-15 22:53 UTC, xeruf approved these changes
Nimm die eine suggestion noch mit rein, denke dann passt es.
Quelle muss nicht verlinkt werden, war bloß ein Gedanke.

2022-11-15 22:53 UTC, xeruf commented on hyperbook/book/faq.md
> +so dass die Garbage Collection häufiger erfolgen und weniger Zeit in Anspruch nehmen.
ja passt

2022-12-06 08:42 UTC, xeruf commented on hyperbook/book/faq.md
> +so dass die Garbage Collection häufiger erfolgen und weniger Zeit in Anspruch nehmen.
> was du mit die eine suggestion meintest?
Wenn du das mit dem anderen Garbage Collctor meinst, dann habe ich das bewusst rausgenommen, weil CMS seit Java 9 nicht mehr zu Verfügung steht.

Die hier meinte ich ;)

2022-12-06 09:25 UTC, merged