Spielanleitung Mississippi Queen Version 0
software-challenge/docs pull request #90
Opened 2023-07-27 10:57 UTC by olofnator

Hi, könntet Ihr da einmal rüber schauen, ich war beispielsweise nicht sicher ob das Sandbank Feld noch drin sein sollte oder nicht und wie das genau mit der Gegenströmung funktionieren sollte.

2023-07-31 12:22 UTC, jnccd requested changes
Was Sandbank und Gegenströmung angeht habe ich genauso wenig Ahnung wie du um ehrlich zu sein xd
Die zugehörige Spieleseite auf Notion wurde noch nicht Aktualisiert https://www.notion.so/softwarechallenge/Mississippi-Queen-ab957ac75fab40feb8b59c586bb2a109, aber vlt weiß @maxblan mehr

2023-07-31 12:22 UTC, jnccd commented on hyperbook/book/spiele/mississippi queen/regeln.md
> +Solange die Regeln der einzelnen Aktionsarten eingehalten werden, können
`Der Aktionsablauf in einem Zug ist also: Beschleunigungsaktion -> Erzeugung der Bewegungspunkte -> Beliebige Kombination der restlichen Aktionen, solange die Aktionspunkte ausreichen und die Regeln eingehalten werden`
Das sollte die Reihenfolge noch klarer machen, kannst du aber auch anders umschreiben.

2023-08-01 06:53 UTC, maxblan commented
> Was Sandbank und Gegenströmung angeht habe ich genauso wenig Ahnung wie du um ehrlich zu sein xd Die zugehörige Spieleseite auf Notion wurde noch nicht Aktualisiert https://www.notion.so/softwarechallenge/Mississippi-Queen-ab957ac75fab40feb8b59c586bb2a109, aber vlt weiß @maxblan mehr

Also es soll so sein, dass in der Mitte eines jeden Segments eine Strömung ist, welche auch in die anderen Segmente übergeht und somit auch deren Richtungen verrät. Wo ich mir auch gerade nicht sicher bin, ist, in welche Richtung die Strömung verlaufen soll, da theoretisch immer ein Bewegungspunkt abgezogen werden soll, wenn man darauf gelangt. Das kann sonst @xeruf beantworten.

2023-08-03 16:39 UTC, jnccd commented
Warum ist das geschlossen 😅

2023-08-09 07:21 UTC, xeruf commented
@olofnator bitte auf die Kommentare von niklas antworten um sicherzugehen, dass sie gelöst sind

2023-08-09 07:33 UTC, xeruf commented on hyperbook/book/spiele/mississippi-queen/regeln.md
> +Über das ganze Spielbrett hinweg zieht sich durch jedes Segment mittig eine Gegenströmung, die zum passieren eine erhöhte Geschwindigkeit benötigt. Die Geschwindigkeit wird wie folgt berechnet: Um n
```suggestion
Über das ganze Spielbrett hinweg zieht sich durch jedes Segment mittig eine Gegenströmung, die zum passieren eine erhöhte Geschwindigkeit benötigt. 
Die Geschwindigkeit wird wie folgt berechnet: Um n Felder in die Mitte zu ziehen, benötigt man n+1 Bewegungspunkte.
```

2023-08-09 07:33 UTC, xeruf commented on hyperbook/book/spiele/mississippi-queen/regeln.md
> +Die orangene Linie in der Abbildung unten wird immer für den Spieler
diese orangene linie stimmt nicht mehr so

2023-08-12 13:44 UTC, merged